### ISSUE TITLE
[feature request] Support tramp locations

### ISSUE THREAD

**Issue by dinkonin** [UndeadKernel/pacfiles-mode#4]
Hi, 
it would be nice to be able to merge files remote computers . Currently If I TRAMP to a remote computer and do `pacfiles-start` it shows the pacsave/pacnew files , but when I try to merge/diff it looks for them on the local machine.

**Comment by UndeadKernel** [comment]
This is indeed an interesting use-case scenario.
Let me see how this could be implemented.

**Comment by UndeadKernel** [comment]
@dinkonin, let me know if the latest changes addresses your issue as you expected.

**Comment by dinkonin** [comment]
Working perfectly thanks.
