### ISSUE TITLE
Update search command to match arch wiki

### ISSUE THREAD

**Issue by doolio** [UndeadKernel/pacfiles-mode#7]
Currently, the search command is:
```
find /etc -name '*.pacnew' -o -name '*.pacsave' 2>/dev/null
```
whereas on the arch wiki it is:
```
find /etc -regextype posix-extended -regex ".+\.pac(new|save)" 2> /dev/null
```
I appreciate they achieve the same result but users might expect them to match? for example, I referred to the wiki first and was all set to use `pacdiff` (which uses `vimdiff`) before discovering your package.

Also, the wiki states one may want to change the search from `/etc` to `/`. You may want to update the search command to search from `/` or at a minimum also state that in the README as I found one pacnew file outside of `/etc` on my system.

In any case, thanks for your time and this package. Yet, another reason I don't have to leave Emacs :).

**Comment by UndeadKernel** [comment]
Hey @doolio. I'm glad the package has helped you. Taming .pacnew files is definitely a pain... until you use ediff and is then such an easy task :D

I know that using the command from the Wiki seems to be right, but I have the feeling that it's not as easy to read as the command I set as default. I was sort of using the philosophy of being as explicit as possible. I think I rather leave the current command as is as both are basically identical.

Regarding the base search path: I'm considering adding a configuration variable to define the base search path. Do you think this would be useful to you?

**Comment by doolio** [comment]
```
it's not as easy to read as the command I set as default.
```
Yes, I agree.

```
Regarding the base search path: I'm considering adding a configuration variable to define the base search path. Do you think this would be useful to you?
```
Yes, I certainly would find that useful. Thanks.

**Comment by UndeadKernel** [comment]
Hey @doolio, after thinking more about it, I believe it is better to leave the configuration of the path as it is now. If I add a new variable to only hold the path, then it becomes hard for the user to configure the search options.

**Comment by doolio** [comment]
That's fine. I trust your better judgement. Thanks for your time.
